### ISSUE TITLE
Can’t start content / streams

### ISSUE THREAD

**Issue by jscheeres** [NoahFetz/F1AppleTV#10]
Version 1.0 (21.325.6)

I can’t start any content, documentaries or streams anymore.

Clicking on a tile/button does not start the stream.

**Comment by jscheeres** [comment]
Logout and login fixes the issue

**Comment by NoahFetz** [comment]
I'll add something in the future that tries this automatically when the request fails

**Comment by NoahFetz** [comment]
Should be fixed in the latest update
