### ISSUE TITLE
Live F2 Practice does not load

### ISSUE THREAD

**Issue by yp28** [NoahFetz/F1AppleTV#11]
Cannot load the F2 Practice when trying to view the live broadcast. It does show up in the list, but clicking it does nothing.

**Comment by NoahFetz** [comment]
Can you try logging out and back in again.

**Comment by rjaakke** [comment]
Same issue, logging out and back in again doesn't fix it for me.

**Comment by NoahFetz** [comment]
Ok I'm working right now, I'll see if I can do anything during lunchtime

**Comment by yp28** [comment]
Let me know if you need help testing @NoahFetz

**Comment by robbinonline** [comment]
I had the same problem. Log out/in no fix. 
Now with FP1 I also can’t open the stream.

**Comment by robbinonline** [comment]
The replay for F2 is also not working. Older videos for yesterday are working fine. If I use another desktop F1 viewer new API it works fine.

**Comment by jonathancregut** [comment]
Same issue here. Can't load live feeds.

**Comment by NoahFetz** [comment]
New version is on the way :)

**Comment by yp28** [comment]
Tested on Apple TV HD, updated through Testflight, verified the with the changelog that I pulled in the new version with that fix, but no dice. Restarted the Apple TV, still does not work.

**Comment by mkkrkhm** [comment]
Works here yp28. There was a new build under testflight, updated and now watching FP1 main feed.

**Comment by yp28** [comment]
> Works here yp28. There was a new build under testflight, updated and now watching FP1 main feed (ATV HD non 4K).

Then there's probably some weird thing going on on my Apple TV HD, will try later.

**Comment by robbinonline** [comment]
It works here with the new build! ATV 4K. 
Awesome for the fast response.

**Comment by NoahFetz** [comment]
> Tested on Apple TV HD, updated through Testflight, verified the with the changelog that I pulled in the new version with that fix, but no dice. Restarted the Apple TV, still does not work.
> 
> Edit: My brother tested on his Apple TV 4K and it works, will verify later today on my own Apple TV 4K, and again on my HD. Maybe there's still some caching in there?

Try the next version, it's currently uploading

**Comment by yp28** [comment]
Awesome, error reporting! Will report back later today.

**Comment by KixAss** [comment]
Great, it works now! Thanks!

**Comment by yp28** [comment]
Works fine now. Thanks for the quick update!
