### ISSUE TITLE
Trying to use TestFlight for f1appletv but link invalid...

### ISSUE THREAD

**Issue by djkeithers** [NoahFetz/F1AppleTV#12]
Can you help me? When I click the link to add F1TV  it tells me that the link is invalid :(

**Comment by djkeithers** [comment]
I get this error 
![AFCFB8B5-49F8-473C-BBC4-E7A599859FA8](https://user-images.githubusercontent.com/81454768/112708592-12edfc80-8e70-11eb-8f69-f03b75c49f10.png)

**Comment by anthonylavado** [comment]
@djkeithers Do you have TestFlight installed on your iPhone?

https://apps.apple.com/ca/app/testflight/id899247664

**Comment by NoahFetz** [comment]
Since you dmed me I'm gonna close this issue.
