### ISSUE TITLE
Not possible to log in.

### ISSUE THREAD

**Issue by Kevin-com** [NoahFetz/F1AppleTV#13]
I’m getting an error that it is not possible to log in. I have a payed account on F1. 

Thank you!

**Comment by NoahFetz** [comment]
Can post the exact error, your language and your country please?

**Comment by Kevin-com** [comment]
> Can post the exact error, your language and your country please?

Hello,

The error is: “Fout bij login” (Login error). I’m from Belgium and my language is Dutch (Flemish).

**Comment by Spen911** [comment]
> > Can post the exact error, your language and your country please?
> 
> Hello,
> 
> The error is: “Fout bij login” (Login error). I’m from Belgium and my language is Dutch (Flemish).

Strange. I'm also from Belgium and don't had any problem to login today. Can you login via your browser https://f1tv.formula1.com/ ?

**Comment by NoahFetz** [comment]
Ok it sounds to me like you have a typo in your Email or Password

**Comment by Kevin-com** [comment]
> Ok it sounds to me like you have a typo in your Email or Password

After a few times

**Comment by NoahFetz** [comment]
Ok then it may have been F1TVs bot detection, it happens sometimes sorry, and no way to detect that 😬
