### ISSUE TITLE
Default audio seems to be German

### ISSUE THREAD

**Issue by rjaakke** [NoahFetz/F1AppleTV#14]
I'm a Dutch user and when I start a stream the audio defaults to German instead of Dutch.
It would be nice if it defaults to your language if available and even better if a use can set a default language.

**Comment by Tedmen** [comment]
Yes, to set a default language would be great. I'm Dutch also, but I prefer to listen to the Englisch commentator, because I don't like the Dutch commentator (Olaf Mol). :-) And thanks Noah for the great app!

**Comment by NoahFetz** [comment]
It should save your preference now
