### ISSUE TITLE
Keep the app alive while buffering

### ISSUE THREAD

**Issue by clausjoergensen** [NoahFetz/F1AppleTV#15]
Today the screen saver will start while buffering (which seems to be a huge problem for F1TV right now), it would be great if the app could stay "active" while buffering.

**Comment by NoahFetz** [comment]
If it's buffering press menu and start it again, it's not buffering for me at least :)

**Comment by clausjoergensen** [comment]
I been unable to get it out of buffering for the main feed today (so watching on desktop instead), I had similar issues on Friday, whereas Qualifying was fine.

**Comment by NoahFetz** [comment]
I'm sorry to hear that, but it seems to be an issue on your side. Maybe try rebooting your AppleTV and network, the usual stuff, can't do any more since I didn't code the player, Apple did 😬

**Comment by clausjoergensen** [comment]
Yeah, I'll checkout the code, and see if I can debug it on my end. I was thinking it might be the auth token had expired, but logging in again didn't help either.

**Comment by NoahFetz** [comment]
It can't be the auth token because it won't get the stream url without a valid token and it won't open the player without the url so it has to be something network related or so

**Comment by clausjoergensen** [comment]
I restarted the AppleTV and deployed locally and zero issues now. At least I can debug it next time it happens :) 

Cheers for the great app!

**Comment by NoahFetz** [comment]
Strange, wonder what the difference is between the testflight build and you running it locally 🤔

**Comment by NoahFetz** [comment]
I'll close this for now since I haven't had any buffering lately.
