### ISSUE TITLE
No audio on English audio channel - Pit Lane Channel 

### ISSUE THREAD

**Issue by mariorsjr** [NoahFetz/F1AppleTV#16]
When the “English audio” is selected on Pit Lane Channel the audio is “muted”. There’s no commentary or car noise. 
cfx audio works. 
this is during live race right now

**Comment by NoahFetz** [comment]
That's an f1tv issue, was the same on testing it's probably on some other channel and they mapped it wrong.

**Comment by mariorsjr** [comment]
Got it. Thanks. 
In the iPhone app it is working good. Hope that they fix that. 
thanks @NoahFetz! And thanks for the app, it’s really great

**Comment by mariorsjr** [comment]
The audio is working now
