### ISSUE TITLE
Simple PiP Mode

### ISSUE THREAD

**Issue by jcreameriii** [NoahFetz/F1AppleTV#20]
I love your in-depth multi-view update! It got me thinking about how I had been watching before, which was airplaying a second feed to my Apple TV for Picture in Picture. I’d like to propose a new enhancement, I think adding a simple PiP mode would be an awesome addition to your app, similar to the native Apple TV experience with two apps (but obviously only with yours). That way you could still focus your attention to one fullscreen feed and then in the bottom right you can keep up with the second feed.

**Comment by NoahFetz** [comment]
If you open a channel in full screen you can use the default pip already

**Comment by jcreameriii** [comment]
Ah I see, had to play around a bit to figure that out. Thanks!
