### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yanick0** [NoahFetz/F1AppleTV#25]
Hi,

When trying to play anything, live or replay or show, I get the following error:

Response validation failed: Response status code was unacceptable: 401.Failure Reason: UnacceptableStatusCode(code401)Response status code was unacceptable: 401
![A07CC4F5-E428-4AFE-963F-3DC30B290B86](https://user-images.githubusercontent.com/83533594/116807352-0aee4000-ab33-11eb-97d6-51e35be96d97.jpeg)

**Comment by NoahFetz** [comment]
401 means something regarding authentication. So either you login is not correct or your country has some restrictions?

**Comment by Yanick0** [comment]
Very strange, I logged out and logged back in, now it works again. Thanks!
