### ISSUE TITLE
Unable to build due to missing SkeletonView package

### ISSUE THREAD

**Issue by grork** [NoahFetz/F1AppleTV#3]
Upon cloning the repo, opening in Xcode, and building there is a build error that SkeletonView can’t be found. Upon adding a reference to the package, there are a number of errors about being unable to find the framework package despite it being listed in frameworks for the project.

(Forgive the lack of fine detail, I’m a n00b to managing packages/frameworks in Xcode)

**Comment by NoahFetz** [comment]
I recommend to use TestFlight but if you really want to build it from
source make sure you open the workspace (White icon) and not the Project
(Blue icon)

Dominic Hopton ***@***.***> schrieb am Fr. 12. März 2021 um
16:50:

**Comment by grork** [comment]
Well colour me a muppet -- serves me right for breezing through the instructions
