### ISSUE TITLE
Commentary track unavailable on some early 2018 races

### ISSUE THREAD

**Issue by grork** [NoahFetz/F1AppleTV#38]
App Version: 21.503.19
tvOS: 14.6

When playing ~Australia~ _(F1 fixed this one)_ & China 2018 it’s not possible to play the commentary track (“English”), and instead only the sound effects track is available. Of note, there are _two_ “English” items, and nothing seems to change when switching between duplicated English audio tracks. (Compared to normally where there is a brief moment of silence as the track switches). Driver feeds seem to have three english items, which seems to only be the driver audio.

Of note, the same races in the F1TV Web & iOS app do correctly list the English & FX tracks correctly, although the mix is wrong, and the “english” is _only_ commentary — no race sound (That obviously is not an app issue).

[Edited to add 'not' at the every end there]

**Comment by NoahFetz** [comment]
I just tried it and I only see one English feed. It's muted in the beginning for about 30 seconds and then there's only commentary. It's the same in the web player for me so it's an issue on their side with the mix. I can't do anything about that.

**Comment by grork** [comment]
First: Apologies for my typo in the final paragraph of my message. I left out a "not". 🤦.

Second: They (F1) appear to have fixed Australia 2018, but China 2018 still experiences the issue. Sorry! (I promise it was repoing on Australia when I reported the issue!)

Third: I've made a fix! #39!

**Comment by NoahFetz** [comment]
Thanks a lot, I'll close this issue since I've tested it and it works now with the fix :)
