### ISSUE TITLE
Seasons only shows the past 4 years

### ISSUE THREAD

**Issue by SDF-7** [NoahFetz/F1AppleTV#4]
Probably a result of the way the new layout on the web page works, but the "Seasons" selection only shows 2021, 2020, 2019 and 2018.  (Past season archives in the https://f1tv.formula1.com/page/493/archive page are grouped in later rows).

It is possible to find past season races via the on-demand listing of "Full Races", but when going back and trying to watch things like "All races from 2010 to present", having the season groupings would be nice.

By no means a showstopper, just an enhancement request if you feel like it. Thanks again for the fantastic app!

**Comment by NoahFetz** [comment]
I'm currently working on implementing the new api and the app is gonna show everything the website has. But it's gonna need some more time until it's finished :)

**Comment by NoahFetz** [comment]
Should be in the newest version
