### ISSUE TITLE
Response serialization failed

### ISSUE THREAD

**Issue by ryusaeba** [NoahFetz/F1AppleTV#43]
Thanks for the great and awesome work, since it can resolve my airplay issue. 
After trying, it works well when playing the free video, such as RADIO REWIND.
However, it will pop the following message when playing the paid video, such as Sunday Race.
Do you have any idea about this?
BTW: I am also using the HOTSPOT from iPhone with NordVPN already.

![unnamed](https://user-images.githubusercontent.com/29192565/129294196-abf00d4c-40a3-48ee-b674-db10b38f29df.jpg)

**Comment by NoahFetz** [comment]
Ok that's strange, but you do have a F1TV Pro account right?
And can you play it from their iOS App or the Browser?

**Comment by ryusaeba** [comment]
Thanks for the response. 
Yes, I have Pro account and can play from iPhome.
I just got apple tv few days ago. Do I have to upgrade tvOS first?

**Comment by NoahFetz** [comment]
No this shouldn't have anything to do with a tvOS update. What country are you from?

**Comment by ryusaeba** [comment]
Taiwan ~ Or I should update country of F1 tv pro account information to us?

**Comment by ryusaeba** [comment]
After login the f1 website, my country in account is already set to US. But the country shown on F1AppleTV app is still Taiwan, as blow shows.
![Uploading ECDCAFB6-E0D7-4913-BC70-DD6EC2CEA7D7.jpeg…]()

**Comment by NoahFetz** [comment]
Well Taiwan doesn't have F1TV Pro so that's why it can't find the token. It's a region block

**Comment by ryusaeba** [comment]
Doesn't the hotspot with VPN resolve this issue? I tried to use NordVPN on Iphone to share the hotspot with Apple TV. I guess this should work. Or iPhone can get token but Apple Tv cannot? 

Thanks again

**Comment by ryusaeba** [comment]
Or do we have a way to change this Country on Apple tv?

**Comment by NoahFetz** [comment]
I don't know how their country detection etc works. You have to ask someone else. It's also not something I can change in the app.

**Comment by ryusaeba** [comment]
Thanks for the discussion. I also find some related information about the country. 
https://stackoverflow.com/questions/1522210/nslocale-currentlocale-always-returns-en-us-not-users-current-language
I am not sure if this can help my case :)

**Comment by NoahFetz** [comment]
No this has nothing to do with the app. The country that's displayed in your case Taiwan comes from F1's API. That's what they think you're from and that's why you don't have access to the content. I'm going to close this now since I can't do anything about that in the app.

**Comment by ryusaeba** [comment]
Thanks for the discussion 😊
