### ISSUE TITLE
Screensaver starts while watching replays

### ISSUE THREAD

**Issue by sbarre** [NoahFetz/F1AppleTV#45]
While watching a replay video (in this case 2021 Belgian Grand Prix F1 FP1), the Apple TV image slideshow screensaver activates after 10 minutes (the time I have set) as if the device was idle and not playing a video.

Audio is still playing in the background behind the screensaver so the video playback does not pause.

I can simply press the menu button to make the screensaver go away and the video comes back (no pause or interruption).

I'm about to watch FP2 and will report back to share if this also happens with live broadcasts.

**Comment by sbarre** [comment]
> Does it do it with the multi feed player or with the fullscreen player?

I was watching a single feed in fullscreen.  

Let me do another test later today after the race to see if I can reproduce reliably.

**Comment by NoahFetz** [comment]
Very strange. I have my screensaver set to 15 minutes and this never happened to me and I use it for every session.
What's your tvOS Version and your screensaver settings?

**Comment by sbarre** [comment]
Sorry for the delayed response!  I tried to reproduce this a few times last weekend and I can't, so we can probably assume this was just a tvOS bug or some kind of one-time thing.

For posterity, my settings are:

- tvOS version 14.7, ATV model is A1842
- Screensaver is Aerial, starts after 5 minutes, show during music and podcasts set to Yes.

I'll close this for now.
