### ISSUE TITLE
Login error 401

### ISSUE THREAD

**Issue by LRvdLinden** [NoahFetz/F1AppleTV#46]
How to fix this error?

![image](https://user-images.githubusercontent.com/77990847/132126253-f6452ccb-eda3-4450-bc8f-ff8d294900a5.jpeg)

**Comment by LRvdLinden** [comment]
![image](https://user-images.githubusercontent.com/77990847/132126277-23c37eef-035a-4e00-a6f3-a850e27ac7e7.jpeg)

**Comment by NoahFetz** [comment]
Had a few people with the same issue, you have to change your password and it should work again. That's the only thing that helped in the other cases.

**Comment by LRvdLinden** [comment]
Yes it works!

**Comment by LRvdLinden** [comment]
Hi, I get this error again. change my password many times. can't login.
