### ISSUE TITLE
Can’t Open the app

### ISSUE THREAD

**Issue by Xaaant** [NoahFetz/F1AppleTV#47]
I just downloaded the app with TestFlight but I can’t open it on my Apple TV. 
When I click on it, it’s closing immediately. There is an orange dot close to the name of the app as well. 

I did something wrong ? 
My Apple TV has the last update.

**Comment by NoahFetz** [comment]
Yeah sorry for that, only happens if you first downloaded the app. Update in a few minutes...

**Comment by NoahFetz** [comment]
Fix is out. Please try it out and report if it worked

**Comment by Xaaant** [comment]
Indeed it’s working perfectly ! Thank you for this quick fix !
