### ISSUE TITLE
Cannot install through TestFlight.

### ISSUE THREAD

**Issue by JalalAlbasri** [NoahFetz/F1AppleTV#48]
Apple TV 4K tvOS 14.7
Installed TestFlight following the instructions, when I click the download button nothing happens. 

The app shows up on the home screen but when I try to open it the error message says “Unable to install F1ATV please try again later”

**Comment by NoahFetz** [comment]
Maybe delete it and download it again?

**Comment by JalalAlbasri** [comment]
Tried that. Same problem. The app does not download to begin with. It shows up on TestFlight but when click the download button the wheel spins and then reset back to a download button.

**Comment by NoahFetz** [comment]
I just tried it on my AppleTV and it worked, also in the TestFlight Portal on my end it doesn't show anything unusual or any warnings. Seems to be an issue on your side?

**Comment by JalalAlbasri** [comment]
https://user-images.githubusercontent.com/3774959/133003710-924be511-313a-4958-bcdc-8d64b25402e6.MOV

Good to know. This is the problem exactly. First time using TestFlight, any suggestions?

**Comment by NoahFetz** [comment]
Wtf that's strange, I've never seen or heard of that before... Maybe restart everything (AppleTV and your Router), and if that doesn't help reinstall the TestFlight App. Maybe it's some weird dns stuff, you don't have a dns vpn setup or anything? You do have enough space left for the installation? No aerial wallpapers which take a lot of space?
