### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by LRvdLinden** [NoahFetz/F1AppleTV#50]
Hi, I have again the login error. I change my password many times, but it wont help. see old ticket -> https://github.com/NoahFetz/F1AppleTV/issues/46#issuecomment-913142928

**Comment by NoahFetz** [comment]
Does your password contain special characters?

**Comment by LRvdLinden** [comment]
yes but that was earlier not a problem

**Comment by NoahFetz** [comment]
Can you try it without them? Had people have the same problem with special characters before

**Comment by LRvdLinden** [comment]
Still got the same error. no special characters and no numbers in it

**Comment by NoahFetz** [comment]
I can't reproduce it on my side I'm sorry. I'll see if there's anything else and I'll let you know. Just for confirmation you can login on their official App right?

**Comment by LRvdLinden** [comment]
Hi yes. I can login into there site.

**Comment by NoahFetz** [comment]
And specifically on the mobile app on your phone?

**Comment by LRvdLinden** [comment]
Hmm strains. I made a ticket add f1. I will keap you posted.

**Comment by NoahFetz** [comment]
Only make tickets for their apps not 3rd party apps or we get into trouble

**Comment by LRvdLinden** [comment]
Im not stupid 😉 
I made a ticket that i cant login de official F1 TV app for ios.
