### ISSUE TITLE
Error 401 repeatedly

### ISSUE THREAD

**Issue by galexkeene** [NoahFetz/F1AppleTV#51]
Have previously had the app work fine but for a while (a month+?) haven't been able to stream anything (with the app - I can watch fine with my computer and/or official app on my phone). Opening the app would show all the current content (including current live feeds), but clicking on them would throw an "Error 401". Finally tried to log out and log back in, but now getting the same Error 401 when trying to log in. Not sure if this is related to a 401 error with HTTP/web browsers, but any notes on how I might fix it? As far as I can tell I'm fully up to date on the app and I've also fully closed and reopened it a few times, but still the same error.

**Comment by NoahFetz** [comment]
Try changing your password, had a few people with the same issue and that
always fixed it. Also if that doesn‘t work remove special characters from it

Alex Keene ***@***.***> schrieb am So. 10. Okt. 2021 um 04:13:

**Comment by galexkeene** [comment]
That worked, thanks! I've been kicked out of my account and had to do a reset before (just happened during this race!!!), but since it was still working elsewhere I thought it must have been some other issue. All good now though, appreciate the quick reply!
