### ISSUE TITLE
Live streams are not working

### ISSUE THREAD

**Issue by xyz4tech** [NoahFetz/F1AppleTV#52]
The streams of the current day (Friday practice) are not working. The red "x" is displayed directly at start of the stream. Older streams like the pre-season tests 2022 or shows work without any problems. In the officiell app the streams of the current day work perfectly.

Edit: Only the live streams and streams shortly after a live broadcast seem to be affected.

**Comment by NoahFetz** [comment]
Hi, thanks for reporting.
Fix should be on TestFlight in a few minutes.

**Comment by xyz4tech** [comment]
Thanks for the quick fix.
