### ISSUE TITLE
Response validation failed

### ISSUE THREAD

**Issue by kartana** [NoahFetz/F1AppleTV#53]
Current issue while trying to log in. Latest Vroom version and last official tvOS on Apple TV 4k.

**Comment by mustberain** [comment]
Same here, free practice live now but its not working.

**Comment by gielie** [comment]
Same here.
Apple TV 4K 2021, validation failed. 

Please fix before Sunday race

**Comment by NoahFetz** [comment]
New build should be on TestFlight in a few minutes.
