### ISSUE TITLE
ATV update now app not working

### ISSUE THREAD

**Issue by Reddwarfusa** [NoahFetz/F1AppleTV#55]
Apple TV updated to 15.4.1 and cannot logi in to my account on F1TV now.  I get an error 403

unacceptablestatuscode Response code was unacceptable.

did the apple  TV update break this awesome app?

**Comment by Reddwarfusa** [comment]
Thanks that makes me breath a sigh of relief.  When it was working on the Mac and the iPad but not apple TV.  Looking forward to the fix.

**Comment by NoahFetz** [comment]
Oh come on, why do they have to do this stuff all the time... 🙄 I'll look into it 🙂

**Comment by NoahFetz** [comment]
Sorry there won't be a fix for Practice tomorrow. Hope I can get it to work for Quali and the Race...

**Comment by NoahFetz** [comment]
Can everybody please try out this (Maybe) fix?
Please Note FP2 is not playable atm because they still have DRM active on there, try it with FP1. This fix is only for logging in. DRM will hopefully follow tomorrow if this here works...

**Comment by Reddwarfusa** [comment]
Just tested!  It let me login and FP1 is working correctly.  So far so good!  Thanks

**Comment by NoahFetz** [comment]
Thanks for the feedback! 😄

**Comment by ed7789** [comment]
Login worked on my side, and I was able to stream FP1.

**Comment by dwerg85** [comment]
I'm afraid login is not working on my end.
![IMG_8164](https://user-images.githubusercontent.com/67799314/162552206-59663679-6767-4125-9f62-9ecca63f9854.jpg)

**Comment by anthonylavado** [comment]
Login worked for me. In Canada, with F1TV Pro.

@dwerg85 Make sure it's been updated in TestFlight on your Apple TV, just in case. Sometimes the automatic update doesn't happen right away. Should be 1.0 (22.409.1).

**Comment by dwerg85** [comment]
It’s updated. But it seems to not be a vroomTV problem. F1TV seems to have completely forgotten I exist. I get an error even if I try to reset my password.

**Comment by troydonaldson** [comment]
Login worked for me in the latest update.

**Comment by Moppe666** [comment]
Hmm, login not working here, Sweden. I can`t login in vroom or f1tv app, i´m logged in to the f1tv app on the phone so i can airplay, i hope i don´t get thrown out.

**Comment by Letsremax** [comment]
Switzerland here! 

I was able to login but i was unable to load any Streams (Quali and Post Race).

On the official F1TV it works.

**Comment by qu1rk3y** [comment]
Works well here, FP1 good!

**Comment by frank-f** [comment]
Login works with the latest version (Germany, F1TV Pro)

**Comment by NoahFetz** [comment]
@dwerg85 Error 401 means wrong Email/Password combination, but that's good that means it got past the bot detection otherwise you would get a 403 error

**Comment by NoahFetz** [comment]
@Moppe666 What error code are you getting?

**Comment by NoahFetz** [comment]
@Letsremax Eyyy an Schwizer wo mini App brucht geil 😂

Yeah that's sue to DRM hopefully I can implement that today..

**Comment by dwerg85** [comment]
> @dwerg85 Error 401 means wrong Email/Password combination, but that's good that means it got past the bot detection otherwise you would get a 403 error

Yeah, I figured out after my post that it wasn’t a Vroom error. But I’m still not 100% what it was. Support asked me to disable any VPN or adblockers I might have going (which I did on both ATV and iPhone, but they also mentioned “unblocking my IP address”. So no clue atm what actually fixed it.

**Comment by Moppe666** [comment]
> 

I had the error 403. Changed password in the f1tv app and i was able to log in to vroom this morning but no streams just a black screen. Now after having watched the race in f1tv app vroom is up and running again, all good.

**Comment by NoahFetz** [comment]
The black screen was because of DRM which I've just fixed so can you test it again with the post race show that is still protected?

**Comment by FelixSFD** [comment]
> The black screen was because of DRM which I've just fixed so can you test it again with the post race show that is still protected?

just tested the new version with the replays of the Qualifying, Race and Post-Race show and it worked 😍
Thank you!

**Comment by Moppe666** [comment]
> The black screen was because of DRM which I've just fixed so can you test it again with the post race show that is still protected?

Yep, it´s still black. The important stuff is working and that´s good enough for me. 👍

**Comment by NoahFetz** [comment]
> > The black screen was because of DRM which I've just fixed so can you test it again with the post race show that is still protected?
> 
> Yep, it´s still black. The important stuff is working and that´s good enough for me. 👍

Are you sure you updated? Which one is still black for you?

**Comment by Moppe666** [comment]
I hadn´t updated, did it now and the post race show is still black. The rest seems to work.

**Comment by NoahFetz** [comment]
Okay, I'll look into it, maybe it's something related to the country because for me it works.

**Comment by Moppe666** [comment]
> Okay, I'll look into it, maybe it's something related to the country because for me it works.

I think i updated again. The update function seems a bit confused and now it´s working.

**Comment by mfilej** [comment]
Can confirm that it works here too.

Your work is much appreciated!

**Comment by dwerg85** [comment]
It is updated I’m afraid.
