### ISSUE TITLE
Livestream suddenly buffering very often

### ISSUE THREAD

**Issue by FelixSFD** [NoahFetz/F1AppleTV#56]
During this weekend's live sessions, I noticed that the stream buffers for a few milliseconds once or twice per minute. During that time, audio cuts out and the video feed sometimes slightly jumps in time. Also the player-controls appear on screen. This does not happen when using the official app or the website, even when running multiple streams at the same time, so I'm quite sure that this has nothing to do with my internet connection.
I never had this issue before, so I think it might have something to do with the DRM fix? #55 

https://user-images.githubusercontent.com/2721240/164887143-d33f253b-565b-421a-817f-d010b14058e0.mov

Bandwidth usage as reported by my router:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2721240/164887228-d158ecc2-be60-4a72-b1f8-948c9fb76bdb.png">

**Comment by steelzeh** [comment]
Yes, experiencing this as well. Buffers and jumps back in time, then buffers and jumps forward sometimes skipping something important. Quite annoying

**Comment by NoahFetz** [comment]
Can't look at this right now since I'm on vacation

**Comment by gielie** [comment]
Same here, also multiple streams not working, lot off buffering stuttering with stopping images.

**Comment by Hinken** [comment]
> Same here, also multiple streams not working, lot off buffering stuttering with stopping images.

Same also here for me.

**Comment by frank-f** [comment]
I have the same problem. I've done some experimenting during less important live sessions and I suspect it is not directly related to this app. If I use Safari to view a live stream within Safari it works without any issues. If I use Airplay to send this very same live stream from Safari to my Apple TV, it starts cutting out all the time, just like it does with this App.
Interestingly, if I use the official iPhone App to stream a live stream via Airplay to the Apple TV, I have no issues.

Maybe any of this is helpful: I am in Germany, I have tried Akamai and Cloudfront, different languages, restarting the Apple TV - no change.

**Comment by NoahFetz** [comment]
Should be fixed with new version
