### ISSUE TITLE
Login Errors

### ISSUE THREAD

**Issue by anthonylavado** [NoahFetz/F1AppleTV#57]
Getting a few reports on Reddit that there are login errors, even after yesterday's update.

I'll see if I can gather any info.

**Comment by NoahFetz** [comment]
You don‘t have to, I know why, login challenge bypass doesn‘t work anymore.
Can‘t do anything right now I‘m not at home

Anthony Lavado ***@***.***> schrieb am Sa. 21. Mai 2022 um
13:48:

**Comment by xollob** [comment]
Yup. Getting a error Response Validation Failed.  403 unacceptableStatusCode at the login prompt.

Thanks for letting us know and saving me the troubleshooting time.

**Comment by strikedamic** [comment]
Getting the same issue also today.

**Comment by NoahFetz** [comment]
Didn't find a way to fix it yet

**Comment by strikedamic** [comment]
That's too bad @NoahFetz — your app and its grid view was actually the reason why I bought F1TV for a season in the first place :D

Anyway, take your time, hope everything is alright on your end.

**Comment by NoahFetz** [comment]
There's no Browser on tvOS. That's why all the services that use OAuth have the system that you open the webpage on your phone or computer and then enter a code that authenticates the device. But I'm looking into using non exposed methods maybe I'm able to open the page in the background and then fetch the Imperva token to register the device properly in their system

**Comment by NoahFetz** [comment]
It works for me again after the fix, can some people confirm this please?

**Comment by NoahFetz** [comment]
Can you show me a picture of the error please?

**Comment by NoahFetz** [comment]
> ![A1428327-0919-4EBF-8682-73BD0EB636F3](https://user-images.githubusercontent.com/68300305/173095570-d7b034c5-682d-4258-a08e-f49a007153e7.jpeg)
> 
> here you go. FYI I'm in California if that helps.

Do you get the login page when you open this link or something else?
https://account.formula1.com/#/login

**Comment by Reddwarfusa** [comment]
Yes I get the login page
<img width="1055" alt="2022-06-10_10-11-20" src="https://user-images.githubusercontent.com/68300305/173117557-50cb7149-e439-42b8-8dda-bfd86dd4e7ce.png">

**Comment by sasagr** [comment]
![image](https://user-images.githubusercontent.com/3427877/173124729-c4ee5079-c338-4703-a473-9d7d7e020ffd.jpg)

not working for me either with the build of today

**Comment by taxidriveer** [comment]
I have the following error after the update:
![error](https://user-images.githubusercontent.com/4417067/173137427-87c54b8e-ba92-475a-999d-c8fe015952ad.jpg)

I do have the login page on other devices when I access https://account.formula1.com/#/login

**Comment by NoahFetz** [comment]
> I have the following error after the update: ![error](https://user-images.githubusercontent.com/4417067/173137427-87c54b8e-ba92-475a-999d-c8fe015952ad.jpg)
> 
> I do have the login page on other devices when I access https://account.formula1.com/#/login

Can you check if you've reached the device limit? You can do this here https://account.formula1.com/#/de/my-subscription

**Comment by NoahFetz** [comment]
> ![image](https://user-images.githubusercontent.com/3427877/173124729-c4ee5079-c338-4703-a473-9d7d7e020ffd.jpg)
> 
> not working for me either with the build of today

You probably waited too long on the login page (The token is only valid for a couple of minutes). I can't explain a 403 otherwise

**Comment by NoahFetz** [comment]
> Yes I get the login page <img alt="2022-06-10_10-11-20" width="1055" src="https://user-images.githubusercontent.com/68300305/173117557-50cb7149-e439-42b8-8dda-bfd86dd4e7ce.png">

Can you also check for the device limit?

**Comment by taxidriveer** [comment]
Thanks @NoahFetz, I deleted a device and I was able to login!

**Comment by Reddwarfusa** [comment]
![6F5E9F98-3C5C-49A9-AE17-7C1F2184D7FD](https://user-images.githubusercontent.com/68300305/173155199-d2d1c6ee-6633-467e-afb6-29d5aebc3637.jpeg)
Unfortunately still the same issue for me even after deleting devices.
![6B6E6231-8B90-4BFA-8FAC-670D906A2479](https://user-images.githubusercontent.com/68300305/173155193-3f1f4bb9-d67c-426c-8c65-3945ddb037b8.png)

**Comment by NoahFetz** [comment]
> 
> 
> ![6F5E9F98-3C5C-49A9-AE17-7C1F2184D7FD](https://user-images.githubusercontent.com/68300305/173155199-d2d1c6ee-6633-467e-afb6-29d5aebc3637.jpeg)
> 
> Unfortunately still the same issue for me even after deleting devices.
> 
> ![6B6E6231-8B90-4BFA-8FAC-670D906A2479](https://user-images.githubusercontent.com/68300305/173155193-3f1f4bb9-d67c-426c-8c65-3945ddb037b8.png)
> 
> 

That's a different key now, do you have your title (Mr/Mrs) set?

**Comment by Reddwarfusa** [comment]
Checked my profile and you got it nailed.  Not sure when that would have changed but thank you for being the cat the continues to chase the mouse!!

**Comment by sasagr** [comment]
> > ![image](https://user-images.githubusercontent.com/3427877/173124729-c4ee5079-c338-4703-a473-9d7d7e020ffd.jpg)
> > not working for me either with the build of today
> 
> You probably waited too long on the login page (The token is only valid for a couple of minutes). I can't explain a 403 otherwise

It looked like I m missing something. I went in the account page of your app and input the email and password in maybe 10-20 secs I got this message. Tried many time but still the same. Do I have to do something else? Open some page outside the Apple TV ?

**Comment by gielie** [comment]
> ![A1428327-0919-4EBF-8682-73BD0EB636F3](https://user-images.githubusercontent.com/68300305/173095570-d7b034c5-682d-4258-a08e-f49a007153e7.jpeg)
> 
> here you go. FYI I'm in California if that helps.

Here in the Netherlands same problem, I can login but I can’t play any video.

**Comment by NoahFetz** [comment]
What happens exactly when you try to play a video?

**Comment by gielie** [comment]
> What happens exactly when you try to play a video?

I can login but I can't play a video, I have looked in my account for the registered devices and there is only 1, I have removed this and loged on again, but same error

![IMG_0265](https://user-images.githubusercontent.com/1062008/173852151-3ffad1c5-5149-40d9-9584-fc62fb36ee10.jpeg)

**Comment by gielie** [comment]
Still couldn’t watch the race today. 

![Uploading AD086A33-AA3C-4FA5-B3CF-CCDB56584864.jpeg…]()
