### ISSUE TITLE
Suggestion: sort in-car camera menu by name instead of number?

### ISSUE THREAD

**Issue by amp64** [NoahFetz/F1AppleTV#59]
I hope this is a simple fix, am about to clone and take a look myself but zero experience on tvOS and XCode (I'm a PC dev).

**Comment by NoahFetz** [comment]
May I ask you why you'd prefer names over driver numbers?

**Comment by amp64** [comment]
Because I have no idea what number anyone is, and I would like to find them by name, which I do know.

**Comment by amp64** [comment]
So I have cloned, built and run it, which is amazing for a PC dude like me. Looking for the code to do this right now.

**Comment by NoahFetz** [comment]
You don't have to do it, I'll probably add a toggle in the settings because if I change it this way there will be some people who want it sorted by the number

**Comment by NoahFetz** [comment]
If you want to try it for yourself it's in the PageOverviewCollectionViewController.swift on line 429
It's in a bad place there so I will do some refactoring or maybe do the rewrite I've planned for a while now
