### ISSUE TITLE
Can't login to latest version

### ISSUE THREAD

**Issue by amp64** [NoahFetz/F1AppleTV#60]
I get a wordy error message "decoding failed(error:DecodingError.keyNotFound(CodingKeys(stringValue PhysicalDevice, intValue, nil), DecodingError.Context(codingPa[], debugDescription: "No value associated with key CodingStrings(stringValue: PhysicalDevice\", intValue: nil), underlyingError:nil)))

This is from the TestFlight version. I have tried to rebuild it from github, but I lost the pairing to my ATV and can't get it back. Old githib build did work earlier today (used it to watch qually) but nuked that as a part of trying to take the latest changes, so had to go back to TestFlight version which gives me this error.

**Comment by NoahFetz** [comment]
You probably reached your device limit, go on the official website and
remove existing unused devices in your account‘s page

Andy Pennell ***@***.***> schrieb am So. 28. Aug. 2022 um
00:15:

**Comment by amp64** [comment]
That was it, had hit the six device limit! All good now.
