### ISSUE TITLE
Login not available / Error

### ISSUE THREAD

**Issue by yeapea** [NoahFetz/F1AppleTV#69]
I have unfortunately since a few versions the problem that I can no longer login. Somehow I managed it last, but I can not remember how it works last time… it‘s really annoying.

I can't use the remote control on the AppleTV or the iPhone on the AppleTV. I mean, I tested both methods.

I attached a screenshot.
Just reinstalled and joined the testflight again. Same error.

TVos up to date, current AppleTV.

![IMG_8962](https://github.com/NoahFetz/F1AppleTV/assets/14827306/bd4d4f9e-711e-47f9-9ad7-8525f1cc8b43)

**Comment by NoahFetz** [comment]
You have probably exceeded your device limit. Remove one device on the website from your account

**Comment by TonyFil8** [comment]
Add-on question regarding this... 
is there a reason why the Vroom App logs me out of the Apple  TV every week? I have to log in every race weekend and once a month log in to F1 website to remove devices, since every time I log in to Vroom it counts it as a device access. 

Thoughts?

**Comment by yeapea** [comment]
> You have probably exceeded your device limit. Remove one device on the website from your account

Thank you! Remove some devices was the solution
