### ISSUE TITLE
The app is not able to process the responses from F1

### ISSUE THREAD

**Issue by Ardrete** [NoahFetz/F1AppleTV#74]
The app is sending messages on every section and this is not able to decode the responses.

**Comment by dirkNlerxst** [comment]
Having the same issue, here's the error (or at least everything that fit in frame before disappearing).

![IMG_2919](https://github.com/user-attachments/assets/b0e31417-00e6-4fc0-b474-af253faad53f)

**Comment by NoahFetz** [comment]
I'll look at it tomorrow. Thanks for pointing it out :)

**Comment by goldsoundz80** [comment]
Same problem here, hope you can fix it as the stream quality on the F1TV app is atrocious! 😳

**Comment by NoahFetz** [comment]
Update is on the way 🫡

**Comment by NoahFetz** [comment]
Out now

**Comment by goldsoundz80** [comment]
Amazing, thanks mate! Much appreciated 👍

**Comment by JoeGasz** [comment]
Thank you so much for taking care of us! We love having the second screen With multiple driversSent from my iPhoneOn Aug 25, 2024, at 10:51 AM, goldsoundz80 ***@***.***> wrote:﻿
Amazing, thanks mate! Much appreciated 👍
