### ISSUE TITLE
Can’t log in since your update today

### ISSUE THREAD

**Issue by goldsoundz80** [NoahFetz/F1AppleTV#75]
Sorry to raise another issue right after you renewed the app, but I can’t seem to log into my account. This happens when I click the login button after entering my details.

![IMG_1601](https://github.com/user-attachments/assets/a9120786-cf74-445e-ab29-f738296248e0)

**Comment by NoahFetz** [comment]
You've reached the device limit. Remove a device on the webpage in your account

**Comment by goldsoundz80** [comment]
Oh of course! I just just checked and Vroom was in there three times 🤣

thanks for your help!
