### ISSUE TITLE
Dutch language incorrect

### ISSUE THREAD

**Issue by pedur** [NoahFetz/F1AppleTV#8]
https://github.com/NoahFetz/F1AppleTV/blob/ffded3df72aa0f26dea359ad379bbb6fb707a60d/F1A-TV/nl.lproj/Localizable.strings#L14

On that line close should be 'sluiten' 
'Dichtbij' means 'close by' 

The rest of the file looks correct to me.

**Comment by NoahFetz** [comment]
Done
