### ISSUE TITLE
Avoid Race Day Spoilers

### ISSUE THREAD

**Issue by exiliox** [NoahFetz/F1AppleTV#9]
SUGGESTION: A way for app to not show information once a race has started. Basically the user has two choices after a race has begun: 1) Bypass race advisement and view app as usual, or 2) choose to watch the completed race. 

A possible third option would be to watch a race already in progress. This could be part of the first option though.

I know the official app did something similar and was hoping your awesome app could do the same thing for those of us that can't watch the race until after it is done. Thank you!

**Comment by NoahFetz** [comment]
I'll close this for now, F1 avoids spoilers pretty well I think and it's (at least to me) not worth the amount of time it would take to do this.
